Added char buffer
UBC-ECE-Sasha/PIM-JPEG pull request #13
Opened 2022-03-26 18:02 UTC by niloo9876

- Had to change the MCU buffer to 30MB for the program to fit into MRAM
- Added a char cache as well as char MCU output buffer (The naming is not the best, but I can change that later)
- The code might not work with the CPU (All decoding on the host), I'll work on changing the CPU code so we can do comparison testing
- Code tested, but I have not done any performance measures.

2022-03-27 13:47 UTC, mkdashti requested changes
Looks good, except you have to make one additional change in jpeg-host.c since with the current changes, you have to copy "MCU_out_buffer" from DPU not "MCU_buffer".
[jpeg-host.c line 96](https://github.com/UBC-ECE-Sasha/PIM-JPEG/blob/c3335b46068f85d949992cfc57aa344f1e72f95e/src/jpeg-host.c#L96)

So, the change would be something like this:
`DPU_ASSERT(dpu_push_xfer(dpus, DPU_XFER_FROM_DPU, "MCU_out_buffer", 0, sizeof(char) * largest_pixel_count * 3,
                           DPU_XFER_ASYNC));`

Other than this, I think this looks great and should reduce copying time from DPU by half!

2022-03-28 19:13 UTC, jnider approved these changes

2022-03-28 19:13 UTC, jnider commented on src/bmp.c
> +  // TODO FIX the code for CPU
just add an issue for this; it's easier to find & remember later

2022-03-28 19:13 UTC, jnider commented on src/dpu/dpu-jpeg-decode.c
> +__dma_aligned char MCU_out_cache[NR_TASKLETS][PREWRITE_SIZE];
This isn't really a cache, but not important for now

2022-03-28 19:13 UTC, jnider commented on src/dpu/dpu-jpeg-decode.c
> +          mram_write(&MCU_out_cache[d->tasklet_id][cache_index], &MCU_out_buffer[mcu_index], MCU_READ_WRITE_SIZE1 >> 1);
I never liked those MCU_READ_WRITE_SIZE macros - it should be defined as: MCU_size * 3
(also not important for now)

2022-03-28 19:13 UTC, jnider commented on src/dpu/dpu-jpeg-decode.c
> +  // due to the horizantal and vertical sampling factors
horizantal -> horizontal

2022-03-28 19:13 UTC, jnider commented on src/dpu/dpu-jpeg-decode.c
> +__mram_noinit char MCU_out_buffer[MEGABYTE(15)]; // 15MB
In a perfect world, you would just 'git squash' these commits together

2022-03-28 19:13 UTC, jnider commented on src/jpeg-host.c
> +    MCU_buffer[dpu_id] = malloc(sizeof(char) * 87380 * 3 * 64);
this still has magic numbers - we'll have to get rid of that eventually

2022-03-28 19:38 UTC, mkdashti approved these changes
Looks good.

2022-03-28 19:39 UTC, merged